import { useEffect, useState } from 'react'
import api from '../../services/api'
import NotificationBell from '../../components/lms/NotificationBell'

export default function ParentProgress() {
  const [children, setChildren] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  useEffect(() => { api.get('/lms/progress/children').then(r => setChildren(r?.data || [])).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  return <div className="min-h-screen bg-slate-50 dark:bg-gray-950 p-4 md:p-8"><div className="max-w-5xl mx-auto space-y-5"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Children's Learning Progress</h1><NotificationBell/></div>{error && <div className="card p-4 text-red-500">{error}</div>}{loading ? <div className="card p-5">Loading progress…</div> : children.map(child => <section className="card p-5" key={child.student?._id}><h2 className="font-bold">{child.student?.name} <span className="text-sm text-gray-400">{child.student?.grade}</span></h2><div className="grid md:grid-cols-2 gap-3 mt-4">{child.courses.map(item => <div className="border rounded-xl p-3 space-y-2" key={item.course._id}><div className="font-semibold">{item.course.title}</div><div className="text-sm text-gray-500">{item.percent}% complete · {item.completedLessons || 0}/{item.lessons} lessons · {item.completed} activities completed</div>{item.assignmentResults?.length > 0 &&   <div className="text-xs"><div className="font-semibold text-gray-600">Assignments</div>{item.assignmentResults.map(result => <div key={result.assignment?._id || result._id} className="text-gray-500">{result.assignment?.title || 'Assignment'}: {result.marks == null ? result.status : `${result.marks}/${result.assignment?.maxMarks ?? '—'}`}{result.feedback && <span> · {result.feedback}</span>}</div>)}</div>}{item.quizResults?.length > 0 && <div className="text-xs"><div className="font-semibold text-gray-600">Quizzes</div>{item.quizResults.map(result => <div key={result._id} className="text-gray-500">{result.quiz?.title || 'Quiz'}: {result.score}/{result.totalMarks}</div>)}</div>}</div>)}</div>{!child.courses.length && <p className="text-sm text-gray-400 mt-3">No published courses.</p>}</section>)}{!loading&&!children.length&&<div className="card p-10 text-center text-gray-400">No linked students.</div>}</div></div>
}
