const router = require('express').Router()
const { protect, authorize } = require('../middleware/authMiddleware')
const c = require('../controllers/attendanceController')

router.use(protect)
router.get('/me', c.me)
router.get('/leaves', c.listLeaves)
router.post('/leaves', c.createLeave)
router.get('/timetable', c.listTimetable)
router.get('/teacher/schedule', c.teacherSchedule)
router.get('/teacher/overview', c.teacherOverview)
router.get('/teacher/attendance/daily', c.teacherAttendanceDaily)
router.get('/teacher/attendance/weekly', c.teacherAttendanceWeekly)
router.get('/teacher/attendance/monthly', c.teacherAttendanceMonthly)
router.get('/teacher/classes', c.teacherClasses)
router.get('/setup', authorize('attendance'), c.setup)
router.get('/teacher/roster', c.teacherRoster)
router.post('/teacher/batch', c.batchAttendance)
router.get('/summary/me', c.myAttendanceSummary)
router.get('/summary/student/:student', c.studentAttendanceSummary)
router.get('/records', authorize('attendance'), c.listAttendance)
router.post('/records', authorize('attendance', 'create'), c.upsertAttendance)
router.patch('/records/:id/lock', authorize('attendance', 'approve'), c.lockAttendance)
router.patch('/records/:id/correct', authorize('attendance', 'edit'), c.correctAttendance)
router.get('/dashboard', authorize('attendance'), c.dashboard)
router.get('/reports', authorize('attendance', 'export'), c.report)
router.get('/low-attendance', authorize('attendance', 'view'), c.lowAttendance)
router.get('/rules', authorize('attendance'), c.listRules)
router.post('/rules', authorize('attendance', 'create'), c.createRule)
router.patch('/rules/:id', authorize('attendance', 'edit'), c.updateRule)
router.post('/timetable', authorize('attendance', 'create'), c.upsertTimetable)
router.delete('/timetable/:id', authorize('attendance', 'delete'), c.deleteTimetable)
router.post('/timetable/:id/override', authorize('attendance', 'edit'), c.overrideTimetable)
router.patch('/leaves/:id/review', authorize('attendance', 'approve'), c.reviewLeave)

module.exports = router
