const router = require('express').Router()
const { protect, authorize } = require('../middleware/authMiddleware')
const c = require('../controllers/lmsController')
const a = require('../controllers/assignmentController')
const q = require('../controllers/quizController')
const m = require('../controllers/materialController')
const p = require('../controllers/progressController')
const upload = require('../middleware/uploadMiddleware')

router.use(protect)
const staff = authorize('lms')
router.get('/summary', staff, c.summary)
router.get('/teachers', staff, c.listTeachers)
router.get('/student/courses', (req,res,next) => req.user.role === 'student' ? next() : res.status(403).json({message:'Students only'}), c.studentCourses)
router.get('/student/courses/:courseId/lessons', (req,res,next) => req.user.role === 'student' ? next() : res.status(403).json({message:'Students only'}), c.studentLessons)
router.put('/student/courses/:courseId/lessons/:lessonId/complete', (req,res,next) => req.user.role === 'student' ? next() : res.status(403).json({message:'Students only'}), p.completeLesson)
router.route('/courses').all(staff).get(c.listCourses).post(c.createCourse)
router.route('/courses/:id').all(staff).put(c.updateCourse).delete(c.deleteCourse)
router.post('/courses/:id/duplicate', staff, c.duplicateCourse)
router.get('/courses/:id/preview', staff, c.previewCourse)
router.route('/courses/:courseId/lessons').all(staff).get(c.listLessons).post(c.createLesson)
router.put('/courses/:courseId/lessons/:id', staff, c.updateLesson)
router.delete('/courses/:courseId/lessons/:id', staff, c.deleteLesson)
router.route('/courses/:courseId/modules').all(staff).get(c.listModules).post(c.createModule)
router.route('/courses/:courseId/modules/:id').all(staff).put(c.updateModule).delete(c.deleteModule)
router.get('/assignments', authorize('lms'), a.list)
router.get('/assignments/:id', authorize('lms'), a.get)
router.post('/assignments', authorize('lms'), a.create)
router.put('/assignments/:id', authorize('lms'), a.update)
router.post('/assignments/:id/submissions', (req, res, next) => req.user.role === 'student' ? next() : res.status(403).json({ message: 'Students only' }), upload.single('file'), a.submit)
router.get('/submissions/:id/attachment', a.downloadAttachment)
router.get('/assignments/:id/submissions', authorize('lms'), a.submissions)
router.put('/assignments/:assignmentId/submissions/:id', authorize('lms'), a.grade)
router.get('/quizzes', authorize('lms'), q.list)
router.post('/quizzes', staff, q.create)
router.put('/quizzes/:id', staff, q.update)
router.delete('/quizzes/:id', staff, q.remove)
router.post('/quizzes/:id/attempts', (req,res,next) => req.user.role === 'student' ? next() : res.status(403).json({message:'Students only'}), q.attempt)
router.get('/quizzes/:id/attempts', staff, q.attempts)
router.post('/materials', staff, upload.single('file'), m.upload)
router.get('/materials/:id/download', authorize('lms', 'export'), m.download)
router.get('/courses/:courseId/materials', authorize('lms'), m.list)
router.get('/progress/me', (req,res,next) => req.user.role === 'student' ? next() : res.status(403).json({message:'Students only'}), p.mine)
router.get('/progress/children', (req,res,next) => req.user.role === 'parent' ? next() : res.status(403).json({message:'Parents only'}), p.parent)
router.get('/reports', authorize('lms', 'export'), p.report)
router.get('/reports/students', authorize('lms', 'export'), p.studentReport)

module.exports = router
