const router = require('express').Router()
const { protect, restrictTo, authorize } = require('../middleware/authMiddleware')
const c = require('../controllers/relationshipController')
router.use(protect)
router.get('/children', (req, res, next) => req.user.role === 'parent' ? next() : res.status(403).json({ message: 'Parents only' }), c.children)
const relationshipAdmin = restrictTo('superadmin', 'admin')
router.post('/parents/link', relationshipAdmin, authorize('relationships','create'), c.linkParent)
router.delete('/parents/link', relationshipAdmin, authorize('relationships','delete'), c.unlinkParent)
router.post('/enrollments', relationshipAdmin, authorize('relationships','create'), c.enroll)
router.get('/enrollments', relationshipAdmin, authorize('relationships','view'), c.listEnrollments)
router.get('/classes', relationshipAdmin, authorize('relationships','view'), c.listClasses)
router.post('/classes', relationshipAdmin, authorize('relationships','create'), c.createClass)
router.get('/sessions', relationshipAdmin, authorize('relationships','view'), c.listSessions)
router.post('/sessions', relationshipAdmin, authorize('relationships','create'), c.createSession)
router.post('/teachers/link', relationshipAdmin, authorize('relationships','edit'), c.linkTeacher)
module.exports = router
