const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const helmet = require('helmet')
const morgan = require('morgan')
const cookieParser = require('cookie-parser')
const mongoSanitize = require('express-mongo-sanitize')
const xss = require('xss-clean')
const rateLimit = require('express-rate-limit')
const path = require('path')
require('dotenv').config()

const app = express()

app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }))
app.use(mongoSanitize())
app.use(xss())
app.use(rateLimit({ windowMs: 15*60*1000, max: 200 }))
app.use('/api/auth/login', rateLimit({ windowMs: 15*60*1000, max: 10 }))
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }))
app.use(express.json({ limit: '10mb' }))
app.use(express.urlencoded({ extended: true, limit: '10mb' }))
app.use(cookieParser())
if (process.env.NODE_ENV === 'development') app.use(morgan('dev'))
app.use('/api/auth',       require('./routes/authRoutes'))
app.use('/api/news',       require('./routes/newsRoutes'))
app.use('/api/events',     require('./routes/eventRoutes'))
app.use('/api/gallery',    require('./routes/galleryRoutes'))
app.use('/api/notices',    require('./routes/noticeRoutes'))
app.use('/api/teachers',   require('./routes/teacherRoutes'))
app.use('/api/alumni',     require('./routes/alumniRoutes'))
app.use('/api/results',    require('./routes/resultRoutes'))
app.use('/api/admissions', require('./routes/admissionRoutes'))
app.use('/api/users',      require('./routes/userRoutes'))
app.use('/api/rbac',       require('./routes/rbacRoutes'))
app.use('/api/settings',   require('./routes/settingsRoutes'))
app.use('/api/whatsapp',   require('./routes/whatsappRoutes'))
app.use('/api/contact',    require('./routes/contactRoutes'))
app.use('/api/fees',       require('./routes/feeRoutes'))
app.use('/api/library',    require('./routes/libraryRoutes'))
app.use('/api/transport',  require('./routes/transportRoutes'))
app.use('/api/lms',        require('./routes/lmsRoutes'))
app.use('/api/notifications', require('./routes/notificationRoutes'))
app.use('/api/relationships', require('./routes/relationshipRoutes'))
app.use('/api/attendance', require('./routes/attendanceRoutes'))

app.get('/api/health', (req, res) => res.json({ status: 'OK', time: new Date() }))
app.use('*', (req, res) => res.status(404).json({ message: 'Route not found' }))
app.use((err, req, res, next) => {
  console.error(err)
  const status = err.statusCode || 500
  res.status(status).json({ message: status >= 500 ? 'Internal server error' : (err.message || 'Request failed') })
})

mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/kidland_school')
  .then(() => { console.log('MongoDB connected'); app.listen(process.env.PORT||5000, () => console.log(`Server on port ${process.env.PORT||5000}`)) })
  .catch(err => { console.error('DB error:', err); process.exit(1) })
