import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import api from '../../../services/api'

const emptyClass = { name: '', sections: '' }
const emptySession = { name: '', startsOn: '', endsOn: '', isCurrent: false }
const emptyEnrollment = { student: '', academicClass: '', section: '', session: '' }

export default function AcademicSetup() {
  const [users, setUsers] = useState([]), [teachers, setTeachers] = useState([]), [publicTeachers, setPublicTeachers] = useState([])
  const [classes, setClasses] = useState([]), [sessions, setSessions] = useState([]), [enrollments, setEnrollments] = useState([]), [search, setSearch] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [classForm, setClassForm] = useState(emptyClass), [sessionForm, setSessionForm] = useState(emptySession), [enrollment, setEnrollment] = useState(emptyEnrollment), [link, setLink] = useState({ parent: '', student: '', relationship: 'Parent' }), [teacherLink, setTeacherLink] = useState({ user: '', teacher: '' })
  const load = () => Promise.all([api.get('/users'), api.get('/lms/teachers'), api.get('/teachers', { params: { limit: 100 } }), api.get('/relationships/classes'), api.get('/relationships/sessions'), api.get('/relationships/enrollments')]).then(([u,t,pt,c,s,e]) => { setUsers(u?.data || []); setTeachers(t?.data || []); setPublicTeachers(pt?.data || []); setClasses(c?.data || []); setSessions(s?.data || []); setEnrollments(e?.data || []) }).catch(e => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { load() }, [])
  const submit = async (url, body, reset) => { try { await api.post(url, body); toast.success('Saved successfully'); reset(); await load() } catch (e) { toast.error(e.message || 'Unable to save') } }
  const students = users.filter(user => user.role === 'student'), parents = users.filter(user => user.role === 'parent')
  return <div className="space-y-5">
    <div><h1 className="text-xl md:text-2xl font-bold">Academic Setup</h1><p className="text-sm text-gray-500 mt-1">Manage classes, academic sessions, enrollments, parent links, and teacher profiles.</p></div>
    {error && <div className="card p-4 text-red-500 text-sm">{error}</div>}
    {loading ? <div className="card p-8 text-center text-gray-400">Loading academic records…</div> : <div className="grid xl:grid-cols-2 gap-5">
      <Panel title="Create class / section"><form className="space-y-3" onSubmit={e => { e.preventDefault(); submit('/relationships/classes', { name: classForm.name, sections: classForm.sections.split(',').map(v => v.trim()).filter(Boolean) }, () => setClassForm(emptyClass)) }}><input className="field" required placeholder="Class name, e.g. Grade 5" value={classForm.name} onChange={e => setClassForm({ ...classForm, name: e.target.value })}/><input className="field" placeholder="Sections, comma separated" value={classForm.sections} onChange={e => setClassForm({ ...classForm, sections: e.target.value })}/><button className="btn-primary">Add Class</button></form><List items={classes} render={item => `${item.name}${item.sections?.length ? ` · ${item.sections.join(', ')}` : ''}`}/></Panel>
      <Panel title="Create academic session"><form className="space-y-3" onSubmit={e => { e.preventDefault(); submit('/relationships/sessions', sessionForm, () => setSessionForm(emptySession)) }}><input className="field" required placeholder="Session name, e.g. 2083" value={sessionForm.name} onChange={e => setSessionForm({ ...sessionForm, name: e.target.value })}/><div className="grid sm:grid-cols-2 gap-3"><input className="field" type="date" required value={sessionForm.startsOn} onChange={e => setSessionForm({ ...sessionForm, startsOn: e.target.value })}/><input className="field" type="date" required value={sessionForm.endsOn} onChange={e => setSessionForm({ ...sessionForm, endsOn: e.target.value })}/></div><label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={sessionForm.isCurrent} onChange={e => setSessionForm({ ...sessionForm, isCurrent: e.target.checked })}/> Current session</label><button className="btn-primary">Add Session</button></form><List items={sessions} render={item => `${item.name} · ${new Date(item.startsOn).toLocaleDateString()} - ${new Date(item.endsOn).toLocaleDateString()}${item.isCurrent ? ' · Current' : ''}`}/></Panel>
      <Panel title="Enroll student"><form className="space-y-3" onSubmit={e => { e.preventDefault(); submit('/relationships/enrollments', enrollment, () => setEnrollment(emptyEnrollment)) }}><Select label="Student" value={enrollment.student} onChange={value => setEnrollment({ ...enrollment, student: value })} options={students}/><Select label="Class" value={enrollment.academicClass} onChange={value => setEnrollment({ ...enrollment, academicClass: value })} options={classes} labelKey="name"/><Select label="Session" value={enrollment.session} onChange={value => setEnrollment({ ...enrollment, session: value })} options={sessions} labelKey="name"/><input className="field" placeholder="Section" value={enrollment.section} onChange={e => setEnrollment({ ...enrollment, section: e.target.value })}/><button className="btn-primary">Save Enrollment</button></form><input className="field mt-5" placeholder="Filter enrollments by student or class" value={search} onChange={e => setSearch(e.target.value)}/><List items={enrollments.filter(item => `${item.student?.name || ''} ${item.academicClass?.name || ''} ${item.session?.name || ''}`.toLowerCase().includes(search.toLowerCase()))} render={item => `${item.student?.name || 'Student'} · ${item.academicClass?.name || 'Class'}${item.section ? ` / ${item.section}` : ''} · ${item.session?.name || 'Session'} · ${item.status}`}/></Panel>
      <Panel title="Link parent to student"><form className="space-y-3" onSubmit={e => { e.preventDefault(); submit('/relationships/parents/link', link, () => setLink({ parent: '', student: '', relationship: 'Parent' })) }}><Select label="Parent" value={link.parent} onChange={value => setLink({ ...link, parent: value })} options={parents}/><Select label="Student" value={link.student} onChange={value => setLink({ ...link, student: value })} options={students}/><input className="field" placeholder="Relationship" value={link.relationship} onChange={e => setLink({ ...link, relationship: e.target.value })}/><button className="btn-primary">Link Parent</button></form></Panel>
      <Panel title="Link teacher user to public Teacher"><form className="space-y-3" onSubmit={e => { e.preventDefault(); submit('/relationships/teachers/link', teacherLink, () => setTeacherLink({ user: '', teacher: '' })) }}><Select label="Authenticated teacher" value={teacherLink.user} onChange={value => setTeacherLink({ ...teacherLink, user: value })} options={teachers}/><Select label="Public teacher record" value={teacherLink.teacher} onChange={value => setTeacherLink({ ...teacherLink, teacher: value })} options={publicTeachers}/><button className="btn-primary">Link Teacher</button></form></Panel>
    </div>}
  </div>
}
function Panel({ title, children }) { return <section className="card p-5"><h2 className="font-bold mb-4">{title}</h2>{children}</section> }
function List({ items, render }) { return <div className="mt-4 space-y-2">{items.map(item => <div className="text-sm text-gray-500 border-t pt-2" key={item._id}>{render(item)}</div>)}</div> }
function Select({ label, value, onChange, options, labelKey = 'name' }) { return <label className="block"><span className="label">{label}</span><select className="field" required value={value} onChange={e => onChange(e.target.value)}><option value="">Select…</option>{options.map(item => <option key={item._id} value={item._id}>{item[labelKey] || item.name} {item.email ? `(${item.email})` : ''} {item.teacherProfile ? `· linked to ${item.teacherProfile.name}` : ''}</option>)}</select></label> }
